{% set name = "webdiff" %}
{% set version = "1.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/webdiff-{{ version }}.tar.gz
  sha256: f8304c52fe435cc7f06e193a31bec2da91ec4c7bcc5cb5a361eaa0201ef4ca16

build:
  entry_points:
    - webdiff = webdiff.app:run
    - git-webdiff = webdiff.gitwebdiff:run
    - git-webshow = webdiff.gitwebshow:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - binaryornot
    - pillow
    - pygithub 2.3.0
    - unidiff ==0.7.5  # https://github.com/danvk/webdiff/issues/236
    - git

test:
  imports:
    - webdiff
  commands:
    # - pip check  # https://github.com/danvk/webdiff/issues/236
    - webdiff --help
    - git-webdiff --help
    - git-webshow --help
  requires:
    - pip

about:
  home: https://github.com/danvk/webdiff/
  summary: Two-column web-based git difftool
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonashaag
